[package]
name = "rv-emu-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdbstub = "0.6.6"
gdbstub_arch = "0.2.4"
rb = "0.4.1"
rodio = "0.19.0"
