[target.riscv32i-unknown-none-elf]
rustflags = ["-C", "panic=abort", "-C", "link-arg=-Tdevice.x", "-C", "link-arg=-Tlink.x",]
[target.riscv32ima-unknown-none-elf]
rustflags = ["-C", "panic=abort", "-C", "link-arg=-Tdevice.x", "-C", "link-arg=-Tlink.x",]
[build]
target = "riscv32i-unknown-none-elf"

